I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 425, in script
    if betnuexiste == "b" :
  File "game/script.rpy", line 425, in <module>
    if betnuexiste == "b" :
NameError: name 'betnuexiste' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 425, in script
    if betnuexiste == "b" :
  File "renpy/ast.py", line 1892, in execute
    if renpy.python.py_eval(condition):
  File "renpy/python.py", line 2249, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "renpy/python.py", line 2242, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 425, in <module>
    if betnuexiste == "b" :
NameError: name 'betnuexiste' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.6.1693
ESGARSI 1.0
Mon Jul 26 20:58:57 2021
